NFS_CORE_PARAM {
    NFS_Port = 2049;
    MNT_Port = 20048;
    NLM_Port = 32803;
    NFS_Protocols = 3,4;
    Enable_UDP = false;
    Manage_Gids_Expiration = 3600;
}

NFSV4 {
    Graceless = true;
}

EXPORT {
    Export_Id = 1;
    Path = /share;
    Pseudo = /share;
    Access_Type = RW;
    Squash = No_Root_Squash;
    SecType = sys,none;
    Transports = TCP;
    Protocols = 3,4;

    FSAL {
        Name = VFS;
    }

    CLIENT {
        Clients = *;
        Access_Type = RW;
        Squash = No_Root_Squash;
        SecType = sys,none;
        PrivilegedPort = false;
    }
}
